-- Platform-default notification templates (tenant_id null). Shops override per event in Settings > Messages.
-- Variables: {customer_name} {job_ref} {amount} {tracking_url} {shop_name} {shop_phone} {job_link} {rider_name}
-- {rider_phone} {plate} {receipt} {device} {status} {expires_at} {reason}

insert into notification_templates (tenant_id, event_key, audience, channel, title, body, critical) values
-- booking & pickup
(null, 'job.pickup_fee_pending', 'customer', 'in_app', 'Pay the pickup fee', 'Pay {amount} to book a rider for your {device}. Job {job_ref}.', false),
(null, 'job.pickup_requested', 'customer', 'sms', null, '{shop_name}: payment received for {job_ref}. A rider is being assigned to collect your {device}. Track: {job_link}', true),
(null, 'job.pickup_requested', 'customer', 'in_app', 'Rider being assigned', 'We are assigning a rider to collect your {device}.', false),
(null, 'job.pickup_requested', 'staff', 'in_app', 'New pickup booked', '{job_ref}: {device} pickup booked by {customer_name}.', false),
(null, 'job.rider_en_route_to_customer', 'customer', 'sms', null, '{shop_name}: {rider_name} ({plate}, {rider_phone}) is on the way to collect your {device}. Scan the rider QR in the app when they arrive. {job_link}', true),
(null, 'job.rider_en_route_to_customer', 'customer', 'in_app', 'Rider on the way', '{rider_name} ({plate}) is heading to you. Have the device and accessories ready.', false),
(null, 'job.pickup_failed', 'customer', 'sms', null, '{shop_name}: the rider could not collect your {device} for {job_ref}. Rebook a pickup here: {job_link}', true),
(null, 'job.pickup_failed', 'staff', 'in_app', 'Pickup failed', '{job_ref}: pickup attempt failed.', false),
(null, 'job.picked_up', 'customer', 'in_app', 'Device handed over', 'Your {device} is with {rider_name} and on its way to {shop_name}.', false),
(null, 'job.in_transit_to_shop', 'customer', 'in_app', 'On the way to the shop', 'Your {device} is in transit. Track: {tracking_url}', false),
(null, 'job.in_transit_to_shop', 'staff', 'in_app', 'Device incoming', '{job_ref}: {device} is on its way to the bench.', false),
-- intake
(null, 'job.received_at_shop', 'customer', 'sms', null, '{shop_name}: we have received your {device} ({job_ref}). We will send the intake summary shortly. {job_link}', false),
(null, 'job.received_at_shop', 'customer', 'in_app', 'Received at the shop', 'Your {device} has arrived. The technician is checking it against what you declared.', false),
(null, 'job.intake_ack_pending', 'customer', 'sms', null, '{shop_name}: our intake check of your {device} differs from what was declared. Please review and acknowledge before we proceed: {job_link}', true),
(null, 'job.intake_ack_pending', 'customer', 'in_app', 'Please review the intake report', 'The technician noted differences from your declaration. Review the photos and acknowledge to continue.', false),
(null, 'job.diagnosing', 'customer', 'in_app', 'Diagnosis in progress', 'Intake confirmed. The technician is diagnosing your {device}.', false),
-- quote
(null, 'job.quote_sent', 'customer', 'sms', null, '{shop_name}: your repair quote for {job_ref} is {amount}. Review, accept or counter by {expires_at}: {job_link}', true),
(null, 'job.quote_sent', 'customer', 'in_app', 'Quote ready', 'Your quote is {amount}. It expires {expires_at}.', false),
(null, 'job.quote_negotiating', 'staff', 'in_app', 'Counter-offer received', '{job_ref}: {customer_name} sent a counter-offer.', false),
(null, 'job.quote_negotiating', 'customer', 'in_app', 'Counter-offer sent', 'We have sent your counter-offer to the technician.', false),
(null, 'job.quote_expired', 'customer', 'sms', null, '{shop_name}: the quote for {job_ref} has expired. Reply in the app to request a new quote or arrange a return: {job_link}', false),
(null, 'job.quote_expired', 'staff', 'in_app', 'Quote expired', '{job_ref}: the quote expired without a response.', false),
(null, 'job.quote_declined', 'staff', 'in_app', 'Quote declined', '{job_ref}: {customer_name} declined the quote. Prepare the device for return.', false),
(null, 'job.return_fee_pending', 'customer', 'sms', null, '{shop_name}: to return your {device} please pay the return delivery fee of {amount}, or choose to collect at the shop: {job_link}', true),
(null, 'job.return_fee_pending', 'customer', 'in_app', 'Return delivery fee', 'Pay {amount} for return delivery, or choose to collect at the shop.', false),
(null, 'job.deposit_pending', 'customer', 'sms', null, '{shop_name}: quote accepted for {job_ref}. Pay the deposit of {amount} to start the repair: {job_link}', true),
(null, 'job.deposit_pending', 'customer', 'in_app', 'Deposit due', 'Pay {amount} to start the repair.', false),
(null, 'job.deposit_pending', 'staff', 'in_app', 'Quote accepted', '{job_ref}: quote accepted, awaiting deposit.', false),
-- repair
(null, 'job.in_repair', 'customer', 'sms', null, '{shop_name}: deposit received. Repair of your {device} has started. Follow progress: {job_link}', true),
(null, 'job.in_repair', 'customer', 'in_app', 'Repair started', 'Deposit received. We will post progress updates here.', false),
(null, 'job.in_repair', 'staff', 'in_app', 'Deposit paid', '{job_ref}: deposit paid, work order is live.', false),
(null, 'job.repair_complete', 'customer', 'sms', null, '{shop_name}: your {device} is repaired and tested. Choose delivery or collection: {job_link}', true),
(null, 'job.repair_complete', 'customer', 'in_app', 'Repair complete', 'Your {device} is ready. Choose where we should deliver it, or collect at the shop.', false),
(null, 'job.final_payment_pending', 'customer', 'sms', null, '{shop_name}: your final balance for {job_ref} is {amount}. Pay to dispatch your {device}: {job_link}', true),
(null, 'job.final_payment_pending', 'customer', 'in_app', 'Final balance due', 'Pay the balance of {amount} and we will dispatch your device.', false),
-- return
(null, 'job.return_requested', 'customer', 'in_app', 'Return being arranged', 'Payment received. We are assigning a rider to bring your {device} back.', false),
(null, 'job.return_requested', 'staff', 'in_app', 'Ready to dispatch', '{job_ref}: paid in full. Hand over to the rider when they arrive.', false),
(null, 'job.rider_en_route_to_shop', 'staff', 'in_app', 'Rider coming for pickup', '{job_ref}: {rider_name} ({plate}) is on the way to collect the device.', false),
(null, 'job.collected_from_shop', 'customer', 'sms', null, '{shop_name}: {rider_name} ({plate}, {rider_phone}) has your {device} and is on the way. Track: {tracking_url}', true),
(null, 'job.collected_from_shop', 'customer', 'in_app', 'On the way to you', '{rider_name} ({plate}) is bringing your {device}.', false),
(null, 'job.in_transit_to_customer', 'customer', 'in_app', 'Almost there', 'Your {device} is in transit to you.', false),
(null, 'job.return_failed', 'customer', 'sms', null, '{shop_name}: the rider could not deliver your {device} ({job_ref}). Rebook delivery or choose collection: {job_link}', true),
(null, 'job.return_failed', 'staff', 'in_app', 'Return delivery failed', '{job_ref}: delivery attempt failed, device is back at the shop.', false),
(null, 'job.delivered', 'customer', 'sms', null, '{shop_name}: your {device} has been delivered. Please confirm and rate the repair: {job_link}', false),
(null, 'job.delivered', 'customer', 'in_app', 'Delivered', 'Please confirm your {device} is as expected and rate the repair.', false),
(null, 'job.ready_for_collection', 'customer', 'sms', null, '{shop_name}: your {device} ({job_ref}) is ready for collection. Show the code in the app at the counter. {job_link}', false),
(null, 'job.ready_for_collection', 'customer', 'in_app', 'Ready for collection', 'Collect your {device} at {shop_name}. Show the collection code in the app.', false),
-- terminal
(null, 'job.closed', 'customer', 'in_app', 'Job closed', 'Thank you for choosing {shop_name}. Your repair is covered by warranty until the date shown on your invoice.', false),
(null, 'job.cancelled', 'customer', 'sms', null, '{shop_name}: job {job_ref} has been cancelled. {reason}', false),
(null, 'job.cancelled', 'customer', 'in_app', 'Job cancelled', 'Job {job_ref} was cancelled. {reason}', false),
(null, 'job.cancelled', 'staff', 'in_app', 'Job cancelled', '{job_ref} cancelled. {reason}', false),
(null, 'job.declined_returned', 'customer', 'in_app', 'Device returned', 'Your {device} has been returned. Thank you for considering {shop_name}.', false),
-- money & misc
(null, 'payment.received', 'customer', 'sms', null, '{shop_name}: received {amount} for {job_ref}. M-Pesa receipt {receipt}. {job_link}', true),
(null, 'payment.received', 'customer', 'in_app', 'Payment received', '{amount} received. M-Pesa receipt {receipt}.', false),
(null, 'progress.update', 'customer', 'in_app', 'Repair update', '{reason}', false),
(null, 'progress.update', 'customer', 'sms', null, '{shop_name} update on {job_ref}: {reason} {job_link}', false),
(null, 'supplementary.sent', 'customer', 'sms', null, '{shop_name}: additional work is needed on your {device}. Review the extra quote of {amount}: {job_link}', true),
(null, 'supplementary.sent', 'customer', 'in_app', 'Additional work quoted', 'The technician found extra work needed: {amount}. Review and respond.', false),
(null, 'reminder.deposit', 'customer', 'sms', null, '{shop_name}: reminder, the deposit of {amount} for {job_ref} is still pending. Pay here: {job_link}', false),
(null, 'reminder.final_payment', 'customer', 'sms', null, '{shop_name}: reminder, your {device} is ready and the balance of {amount} is pending: {job_link}', false),
(null, 'reminder.dropoff', 'customer', 'sms', null, '{shop_name}: your {device} is ready. Please choose delivery or collection: {job_link}', false),
(null, 'alert.unclaimed', 'staff', 'in_app', 'Unclaimed device', '{job_ref}: {device} has been waiting for the customer for several days.', false),
(null, 'alert.unclaimed', 'staff', 'sms', null, '{shop_name} alert: {job_ref} ({device}) is unclaimed. Customer: {customer_name}.', false),
(null, 'alert.not_as_expected', 'staff', 'in_app', 'Customer flagged an issue', '{job_ref}: {customer_name} says the device is not as expected. {reason}', false),
(null, 'dispute.opened', 'staff', 'in_app', 'Dispute opened', '{job_ref}: {customer_name} opened a dispute. {reason}', false),
(null, 'intake.summary', 'customer', 'sms', null, '{shop_name}: intake summary for {job_ref}: {reason} {job_link}', false),
(null, 'intake.summary', 'customer', 'in_app', 'Intake summary', '{reason}', false);
