/**
 * Generates db/migrations/0002_state_machine.sql from lib/core/state-machine.ts.
 * Run: npm run gen:state-machine   (tests fail if the committed file is stale)
 */
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { ACTOR_KINDS, JOB_STATUSES, TIMER_ALIVE_IN, TIMER_KINDS, TRANSITIONS, allowedActors, type JobStatus } from '../lib/core/state-machine';

const q = (s: string) => `'${s}'`;

export function generateStateMachineSql(): string {
  const lines: string[] = [];
  lines.push('-- GENERATED by scripts/gen-state-machine.ts from lib/core/state-machine.ts. Do not edit by hand.');
  lines.push('');
  lines.push(`create type job_status as enum (\n  ${JOB_STATUSES.map(q).join(',\n  ')}\n);`);
  lines.push('');
  lines.push(`create type actor_kind as enum (${ACTOR_KINDS.map(q).join(', ')});`);
  lines.push('');
  lines.push(`create type timer_kind as enum (${[...TIMER_KINDS, 'payment_reconcile', 'retention_sweep'].map(q).join(', ')});`);
  lines.push('');
  lines.push('create table job_transitions (');
  lines.push('  from_status job_status not null,');
  lines.push('  to_status job_status not null,');
  lines.push('  allowed_actors actor_kind[] not null,');
  lines.push('  primary key (from_status, to_status)');
  lines.push(');');
  lines.push('');
  lines.push('insert into job_transitions (from_status, to_status, allowed_actors) values');
  const rows: string[] = [];
  for (const from of JOB_STATUSES) {
    for (const to of Object.keys(TRANSITIONS[from]) as JobStatus[]) {
      rows.push(`  (${q(from)}, ${q(to)}, array[${allowedActors(from, to).map(q).join(', ')}]::actor_kind[])`);
    }
  }
  lines.push(rows.join(',\n') + ';');
  lines.push('');
  lines.push('create table timer_alive_in (');
  lines.push('  kind timer_kind primary key,');
  lines.push('  statuses job_status[] not null');
  lines.push(');');
  lines.push('');
  lines.push('insert into timer_alive_in (kind, statuses) values');
  lines.push(
    (Object.keys(TIMER_ALIVE_IN) as (keyof typeof TIMER_ALIVE_IN)[])
      .map((k) => `  (${q(k)}, array[${TIMER_ALIVE_IN[k].map(q).join(', ')}]::job_status[])`)
      .join(',\n') + ';',
  );
  lines.push('');
  return lines.join('\n');
}

if (process.argv[1] && /gen-state-machine\.ts$/.test(process.argv[1])) {
  const out = path.join(__dirname, '..', 'db', 'migrations', '0002_state_machine.sql');
  writeFileSync(out, generateStateMachineSql());
  console.log(`wrote ${out}`);
}
